### ISSUE TITLE
Convert to float should handle european string values "9,99" better

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-filter-mutate#100]
from AMA in London elasticon 2017

**Comment by guyboertje** [comment]
A solution to this issue must anticipate thousands separation too.
See [this wikipedia article](https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use)

`1,234,567.89` English speaking countries - ex UK colonies etc.
`1 234 567.89` SI style as above
`1.234.567,89` Mainland European + colonies
`1 234 567,89` SI style as above.

NOTE:
`In the Arab world, where Eastern Arabic numerals are used for writing numbers, a different character is used to separate the integer and fractional parts of numbers. It is referred to as an Arabic decimal separator (٫) (in hex U+066B) in Unicode. An Arabic thousands separator (٬) also exists.`

A Java solution using NumberFormat is OK but not without flaws.  See the section `UnexpectedResults.equals(bigTrouble)` in [this link](https://www.ibm.com/developerworks/java/library/j-numberformat/index.html).

**Comment by AbdulHaseebHussain** [comment]
Anticipating thousands operator could cause unexpected results e.g. would 1,000 be converted to 1000.0 based on thousands conversion or to 1.0 based upon european style decimal marks. How can we account for this?

**Comment by guyboertje** [comment]
Exactly. We need a way of letting the user give us a hint.

Sorry to mess you around. In investigating this I wrote all the code changes, so I will be submitting a PR.

**Comment by AbdulHaseebHussain** [comment]
That's great, as long as the issue is resolved.
