### ISSUE TITLE
[Error] Unknown setting 'copy' for mutate

### ISSUE THREAD

**Issue by TaurusD** [logstash-plugins/logstash-filter-mutate#102]
- Version: the most updated one cuz I just re-installed it in Logstash 5.4.2
- Operating System: Win 10
- Config File (if you have sensitive info, please remove it):
`mutate {
		copy=> {	
			"[Longitude]" => "[geo_location][lon]"
			"[Latitude]" => "[geo_location][lat]"
		}
	}`

- Sample Data: [Longitude] and [Latitude] are float, and [geo_location] is pre-defined `geo_point` in Kibana.  

I ran this command `bin\logstash -f first-pipeline.conf --config.reload.automatic` and get:
`[2017-07-14T09:57:45,923][ERROR][logstash.filters.mutate  ] Unknown setting 'copy' for mutate`
`[2017-07-14T09:57:45,930][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Something is wrong with your configuration."}`

**Comment by wiibaa** [comment]
Hello @TaurusD , the version of the plugin are fixed when packaging logstash, so a re-installation will not fetch the most updated one. You can check a speficic plugin version using
`bin/logstash-plugin list --verbose <plugin-name>logstash-filter-mutate`
In 5.4.2: this give

    bin/logstash-plugin list --verbose logstash-filter-mutate
    logstash-filter-mutate (3.1.3)

And the copy option was introduced in next version. You have to manually update the plugin to the latest version with the command `bin/logstash-plugin update logstash-filter-mutate` and you will be able to use the copy method

    bin/logstash-plugin update logstash-filter-mutate
    Updating logstash-filter-mutate
    Updated logstash-filter-mutate 3.1.3 to 3.1.5

**Comment by TaurusD** [comment]
@wiibaa Hi, thank you for your answer! I got the right version now. 
Please let me close this issue.
