### ISSUE TITLE
Feature request: capitalize

### ISSUE THREAD

**Issue by steeevieee** [logstash-plugins/logstash-filter-mutate#105]
Would it be possible to support "capitalize" on fieldnames, in the same way you support "lowercase" ? We have historical data, most of which uses capitalized fieldnames but some uses random cases, so I don't want to retrospectively convert it all to lowercase

**Comment by jsvd** [comment]
this is indeed possible, feel free to submit a patch, the feature seems simple to implement, following the [implementation of upcase](https://github.com/logstash-plugins/logstash-filter-mutate/blob/master/lib/logstash/filters/mutate.rb#L337-L360)

As an alternative, you can use the ruby filter `filter { ruby { code => "event.set('[field]', event.get('[field]').capitalize" } }`
