### ISSUE TITLE
Capitalize mutation not recognized

### ISSUE THREAD

**Issue by FreeYourMinds** [logstash-plugins/logstash-filter-mutate#124]
# Capitalize mutation not accessable

Trying to use the `capitalize` mutation results in an error message.

## Post on forum

My post [Unknown setting capitalize for mutate error](https://discuss.elastic.co/t/unknown-setting-capitalize-for-mutate-error/127616?u=freeyourminds) was closed after the inactivity threshold was reached.
 
## Environment

- ELK: 6.2.2.
- OS: Windows Server 2012R2
- Config: See example below
- Steps to reproduce:
   - Try to apply the capitalize mutation on a custom field

## Config snippet

```
if [LogLevel] {
  mutate {
     capitalize => [ "LogLevel" ]
  }
}
```

## Result

Logstash fails to load its configuration, reporting in the log:

> [ERROR][logstash.filters.mutate ] Unknown setting 'capitalize' for mutate

## Additional information

This only applies to the `capitalize` mutation, using `lowercase` or `uppercase` instead works fine.

Kind regards
FYM

**Comment by jsvd** [comment]
[capitalize was introduced in version 3.3.0 of this plugin](https://github.com/logstash-plugins/logstash-filter-mutate/blob/master/CHANGELOG.md#330), make sure you're using this version by updating logstash or just this individual plugin
