### ISSUE TITLE
Memory leak via mutate

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-filter-mutate#13]
When using the following pattern in a mutate filter:

```
mutate { remove_field => [ "%{[syslog][timestamp]}" ] }
```

It's the "subleveling" that creates this, as it does not occur with toplevel fields.

------------------------------
comment: 

I have been fighting this memory leak with a toplevel field.
```
mutate {
replace => [ "@message", "%
{Message}" ]
remove_field => [ "%{Message}
" ]
}
```
Workaround for me was to use:
```
mutate
{ rename => [ "Message", "@message" ] }
```

migrated from: https://logstash.jira.com/browse/LOGSTASH-1688

**Comment by untergeek** [comment]
Closing this one.
