### ISSUE TITLE
Documentation layout error

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-filter-mutate#14]
Because of the break between lines in the comments, the render is incorrect.  It should be a "code" block, but it's interrupted because of the space there.

The break in question is the one between

```
  #           "fieldname", "/", "_",
```

and

```
  #           # replace backslashes, question marks, hashes, and minuses with
```

The full block currently looks like this:

```
  # Convert a string field by applying a regular expression and a replacement.
  # If the field is not a string, no action will be taken.
  #
  # This configuration takes an array consisting of 3 elements per
  # field/substitution.
  #
  # Be aware of escaping any backslash in the config file.
  #
  # Example:
  # [source,ruby]
  #     filter {
  #       mutate {
  #         gsub => [
  #           # replace all forward slashes with underscore
  #           "fieldname", "/", "_",
  #
  #           # replace backslashes, question marks, hashes, and minuses with
  #           # dot
  #           "fieldname2", "[\\?#-]", "."
  #         ]
  #       }
  #     }
  #
  config :gsub, :validate => :array
```

**Comment by untergeek** [comment]
## Before
> ![Before fix](https://dl.dropboxusercontent.com/u/1085030/gsub_before.png)

## After
> ![After fix](https://dl.dropboxusercontent.com/u/1085030/gsub_after.png)

The fix is just to add an inline comment `#` inside the quoted Ruby code.

**Comment by untergeek** [comment]
## Option B
Just remove the comment line:
> ![Option B](https://dl.dropboxusercontent.com/u/1085030/gsub_optionB.png)

**Comment by untergeek** [comment]
## Revision C
Since `# dot` bothered @kurtado, I've rearranged the text to read better and still not exceed 80 chars per line:
> ![Revision C](https://dl.dropboxusercontent.com/u/1085030/gsub_revisionC.png)

**Comment by suyograo** [comment]
Thanks @untergeek Revision C looks good

**Comment by kurtado** [comment]
```
   # thank
   # you
```
