### ISSUE TITLE
add_field adds boolean values as string

### ISSUE THREAD

**Issue by babadofar** [logstash-plugins/logstash-filter-mutate#20]
When using mutate add_field trying to add fields as boolean, the field is added as string. Can be seen both with rubydebug and json output
Tested on windows in logstash 1.4.2, 1.5.0.rc2 and also latest version pulled from github.
 logstash-1.5.0.rc2\bin\logstash.bat agent -e 'filter{mutate{add_field => {"isthisbool" => false}}} output{stdout {codec => json}}' fisk {"message":"fisk\r","@version":"1","@timestamp":"2015-04-10T09:24:40.573Z","type":"stdin","host":"CV-E6420","isthisbool":"false"} 
In this sample, "isthisbool" should have been false, not "false".

**Comment by untergeek** [comment]
This problem is in the [base filter code](https://github.com/elastic/logstash/blob/3eb5ba6450a2c241d469cc1740c5c46cc7509f02/lib/logstash/filters/base.rb#L162-L177).  Re-opening the [original issue](https://github.com/elastic/logstash/issues/2987).

**Comment by untergeek** [comment]
Playing the yo-yo, here, and re-opening this issue.  We're going to put the fix here instead, as an explicit convert option:

```
mutate {
  convert => { "fieldname" => "boolean" }
}
```

**Comment by untergeek** [comment]
Fixed by #22
