### ISSUE TITLE
Mutate filter (gsub) not working when fieldname contains period

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-mutate#29]
(This issue was originally filed by @clay584 at https://github.com/elastic/logstash/issues/2092)

---

When trying to do a mutate gsub on a field in which the fieldname contains a period (i.e. - netflow.protocol), gsub is not working.  If I use a field that has no period in the name, it works fine.

Current config:
https://gist.github.com/clay584/a45871a73e911ff0ccbd

Sample data showing that the field is not updated:
https://gist.github.com/clay584/cac6126aee96ce85b26a

**Comment by purbon** [comment]
Relates somehow to #30

**Comment by purbon** [comment]
@clay584 I was trying to reproduce your issue locally and was not able to do it. I added an small rspec test like

```
  describe "#gsub" do
    let(:config) do
      { "gsub" => ["a.b", "foo", "bar"] }
    end

    let(:attrs) { { "a.b" => "foo" } }

    it "should rename a.b" do
      subject.filter(event)
      expect(event["a.b"]).to eq("bar")
    end
  end
``` 

and all pass green like expected, can you provide more details of this issue so we are able to reproduce?

Thanks a lot for your report,

/cheers

**Comment by guyboertje** [comment]
This is not a bug. The field is nested and needs to be `"[netflow][protocol]"`.
