### ISSUE TITLE
Feature: Enable use of field referencing in the field names for mutate actions.

### ISSUE THREAD

**Issue by electrical** [logstash-plugins/logstash-filter-mutate#3]
In some cases one creates a new field based on an extracted name using the add_field method.
Sometimes the value of that needs to be converted.
At the moment the mutate filter actions don't support the field ref option.

**Comment by purbon** [comment]
This got partially implemented in https://github.com/logstash-plugins/logstash-filter-mutate/commit/63755ef716b94d8f8d57bb7b3043b5a9337ce509, is your request to have this for all actions?

**Comment by colinsurprenant** [comment]
I believe it does @purbon ... closing.
