### ISSUE TITLE
strip not removing leading and trailing whitespace

### ISSUE THREAD

**Issue by naisanza** [logstash-plugins/logstash-filter-mutate#35]
I'm importing in a CSV, there are columns that have a leading or trailing whitespace, such as:

```
"Site":"Dairy Farm ","Path":" /store.php"
```

I'm using the following filter:

```
mutate {
		strip => [ "Site", "Path" ] }
```

However, when imported in, the whitespaces still exist. I am wondering if there is something that I'm overlooking

I'm running the following versions of elasticsearch and logstash
```
elasticsearch-1.5.2
logstash_1.5.0-1_all
kibana-4.0.2-linux-x64
```

Thanks!

**Comment by purbon** [comment]
As you could see in #50 I write down some test to validate this, and found no issue in the plugin side that I was able to reproduce. I would request more details if you are still hitting this issue so we might be able to reproduce.

You could also use the https://discuss.elastic.co/ forums when looking for troubleshooitng help, the community there is awesome and you will get most probably the answer you might be looking for. 

I will close this issue for now, feel free to reopen with more feedback if we're able to reproduce your issue. 

Thanks a lot for your report.
