### ISSUE TITLE
Failed to remove array element

### ISSUE THREAD

**Issue by rafaltrojniak** [logstash-plugins/logstash-filter-mutate#36]
When using rename on array element, the plugin fails on removing array element.

Example event :
```json
{
  "results": [
    {
      "id": "a1",
      "name": "hello"
    },
    {
      "id": "a2",
      "name": "logstash"
    }
  ]
}
```
Rules:
```
    mutate {
      rename => [ "[results][1]" , "result" ]
    }
```
Exception:
```
{
  :timestamp=>"2015-06-05T00:12:08.517000+0200",
  :message=>"Exception in filterworker",
  "exception"=>#<NoMethodError: undefined method `delete_at' for #<Java::JavaUtil::ArrayList:0xf65618>>,
  "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/util/accessors.rb:52:in `del'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/event.rb:204:in `remove'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-0.1.8/lib/logstash/filters/mutate.rb:240:in `rename'",
    "org/jruby/RubyHash.java:1341:in `each'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-0.1.8/lib/logstash/filters/mutate.rb:238:in `rename'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-0.1.8/lib/logstash/filters/mutate.rb:211:in `filter'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:162:in `multi_filter'",
    "org/jruby/RubyArray.java:1613:in `each'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:159:in `multi_filter'",
    "(eval):67:in `filter_func'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:219:in `filterworker'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:156:in `start_filters'"],
  :level=>:error
  }
```

**Comment by rafaltrojniak** [comment]
After little digging through that, it looks like it was not picket by Unit tests, because they use ruby arrays, instead of Jruby arrays. https://github.com/rafaltrojniak/logstash-filter-mutate/blob/jruby_array/spec/filters/mutate_spec.rb#L445
Please see that branch for the test that fails with :
```
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.....................F...

Failures:

  1) LogStash::Filters::Mutate Removing element from an array "{"array":[{"id":1},{"id":2}]}" when processed
     Failure/Error: pipeline.filter(e) { |filtered_event| results << filtered_event }
     NoMethodError:
       undefined method `delete_at' for #<Java::JavaUtil::ArrayList:0x3e694b3f>
     # ./lib/logstash/filters/mutate.rb:240:in `rename'
     # ./lib/logstash/filters/mutate.rb:238:in `rename'
     # ./lib/logstash/filters/mutate.rb:211:in `filter'
     # (eval):33:in `filter_func'
     # ./spec/filters/mutate_spec.rb:449:in `(root)'
     # ./spec/filters/mutate_spec.rb:449:in `(root)'

Finished in 0.95 seconds
25 examples, 1 failure
```

**Comment by talevy** [comment]
@colinsurprenant does it make sense to add this case here? https://github.com/elastic/logstash/blob/master/lib/logstash/java_integration.rb?

**Comment by rafaltrojniak** [comment]
@talevy  That might do the trick, but I'm not an ruby/jruby expert and I don't know how to write and test it.

**Comment by guyboertje** [comment]
@colinsurprenant - can you confirm that JrJackson is the only mechanism through which a Java::JavaUtil::ArrayList enters the pipeline?

we can:
- wait for JrJackson 0.3.0 (no more Java::JavaUtil::ArrayList)
- or patch the Accessor#del method to use remove(int) if the target responds_to(:remove) as Java::JavaUtil::ArrayList has a remove method, it being functionally equivalent to delete_at in Ruby Array

**Comment by colinsurprenant** [comment]
good catch @rafaltrojniak - thanks for reporting it.

@guyboertje yes, the only way that we can have `ArrayList` or `LinkedHashMap` in the event is when deserializing json with JrJackson.

For a short term fix, as suggested by @talevy, I think I'd prefer to add the `delete_at` method in the `java::util::Collection` module in https://github.com/elastic/logstash/blob/5bb9eb9fb31841421f280ff0f79f9f5273b70b81/lib/logstash/java_integration.rb#L68-L99 which would cover any other usage of `delete_at` instead of localizing the fix in the `Accessors` class.

Makes sense?

**Comment by guyboertje** [comment]
I am looking at this issue in the riemann output too https://github.com/logstash-plugins/logstash-output-riemann/issues/9.  It also requires a method patch to java_integrations.

**Comment by guyboertje** [comment]
The bug is in logstash core.  I will be looking at it shortly.

**Comment by guyboertje** [comment]
JrJackson v0.3.6 is used in LS v1.5.5 and v2.0.0+

@rafaltrojniak - were you able to upgrade to v2 or 1.5.5?

**Comment by elvarb** [comment]
I'm running into this same issue running Logstash 2.1.1, no matter how I define the remove_field option nothing happens

**Comment by elvarb** [comment]
Workaround is to rename the field first and then remove it

      mutate {
        rename => {"[nested][Field]" => "[nestedField]"}
        remove_field => ["nestedField"]
      }

**Comment by guyboertje** [comment]
Closing - LS does not use Java ArrayList on the Ruby side anymore.
