### ISSUE TITLE
Add 'copy_field' functionality

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-filter-mutate#39]
Currently to copy a field one must use `add_field` with a sprintf style statement. This is confusing to newbies and not semantically rich. I propose we add a `copy_field` statement that solves this.

**Comment by purbon** [comment]
++ This makes complete sense to me, however I wonder why a user would like to copy a field? do you have a use case in mind?

**Comment by purbon** [comment]
@andrewvc closing this as duplicate of #12
