### ISSUE TITLE
First line of "replace" option's documentation missing when rendered

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-filter-mutate#41]
It seems the first line from the markup of the documentation of the "replace" option is lost when rendered and [published on elastic.co](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-replace). In other words,

      # Replace a field with a new value. The new value can include %{foo} strings
      # to help you build a new value from other parts of the event.

in the source code becomes just

> to help you build a new value from other parts of the event.

when rendered. Is it perchance "%{foo}" that trips the doc generation script?

**Comment by purbon** [comment]
Thanks for your report @magnusbaeck, are you willing to provide a fix for that?, I guess the error might be where you actually think, although testing this for now might be a bit tricky, you would need to:

* Do the fix in the plugin.
* Build the gem (dot gem file) out of it.
* Install it locally in your logstash.
* Run the task rake docs:generate-docs in your logstash

then you will see the generated output.

we are working on improving this experience for the plugins so documentation could be tested easily.

**Comment by magnusbaeck** [comment]
I can have a look at it. However, I recently changed employer so there's no CLA in place yet so it might take a while (weeks) before I can upload anything.

**Comment by purbon** [comment]
I had to try! feel free to contribute back when possible! everything is more than welcome @magnusbaeck !! thanks a lot for your time and good luck with your new adventures!

**Comment by magnusbaeck** [comment]
This was actually fixed in #60 but the issue reference in that commit message was broken so this issue wasn't properly referenced.
