### ISSUE TITLE
Lowercase fails when text is already all lowercase

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-filter-mutate#44]
Reported by @alaphoid in closed PR 43.

Unverified. Test coverage missing (by me) for this case.

**Comment by suyograo** [comment]
@guyboertje can we get this in ASAP?

**Comment by suyograo** [comment]
Related https://github.com/logstash-plugins/logstash-filter-mutate/issues/44

**Comment by guyboertje** [comment]
Changes to the tests show that this bug is unrelated to the ArrayList from JSON issue. Investigating now.

**Comment by guyboertje** [comment]
Submitting PR now

**Comment by guyboertje** [comment]
Fix is released, gem is published
