### ISSUE TITLE
Upper/lowercase removes field if actionable string is not found

### ISSUE THREAD

**Issue by chandlermelton** [logstash-plugins/logstash-filter-mutate#46]
Using the uppercase or lowercase functions will remove a field if it cannot take an action on it. It should leave the field as-is if it cannot find anything to change.

In the example, providing the string E-E to uppercase deletes the message. It should leave it as E-E. A similar issue is present with lowercase using only lowercase letters.

$ /opt/logstash/bin/logstash -e 'input{ stdin{} } filter { mutate { uppercase => [ "message"] } } output { stdout {} }'
Logstash startup completed
$ e-E
E-E
$ e-e
E-E
$ E-E
%{message}

**Comment by jsvd** [comment]
Issue #44 reported this, and was fixed in https://github.com/logstash-plugins/logstash-filter-mutate/pull/45.
A new version of this plugin was released, which included this fix, can you try doing `bin/plugin update logstash-filter-mutate` and trying again?

**Comment by chandlermelton** [comment]
Confirmed updating from 1.0.1 to 1.0.2 fixes the issue. Closing this one.

Thanks!
