### ISSUE TITLE
Cumbersome to to convert from float to boolean

### ISSUE THREAD

**Issue by cwurm** [logstash-plugins/logstash-filter-mutate#47]
Converting from a `float` to a `boolean` (i.e. from `0.0` to `false` and from `1.0` to `true`) is surprisingly hard to do:
1. As `convert` does not accept `float` as a source type for conversion to `boolean` we first have to convert to `integer`.
2. Unfortunately, this converts the underlying Ruby data type to `Fixnum` and because that class does not have an `empty?` method a conversion to `boolean` fails with an exception (`NoMethodError`).
3. So instead, we have to convert the `integer` to a `string`.
4. Only now can we convert the `string` to a `boolean`.

Accordingly, the config for this looks something like this, with three separate `mutate` sections as it is not possible to combine the `convert`s in one `mutate`:

```
  mutate {
    convert => {
      "field1" => "integer"
    }
  }

  mutate {
    convert => {
      "field1" => "string"
    }
  }

  mutate {
    convert => {
      "field1" => "boolean"
    }
  }
```

**Comment by rajasaur** [comment]
Item (2) above is also a problem when you have a number that needs to be converted to boolean. It fails with a  "undefined method `empty?' for 0:Fixnum " error even though the documentation says 0 will be considered a false. 
Looks like this was changed at https://github.com/logstash-plugins/logstash-filter-mutate/commit/3a3a115e476eaa3ed7542cac32833ceaa3817297
