### ISSUE TITLE
filter method performance

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-filter-mutate#5]
I think we can improve the performance of the `filter` method by replacing the ["linear" if sequence evaluation] (https://github.com/logstash-plugins/logstash-filter-mutate/blob/master/lib/logstash/filters/mutate.rb#L207-L218) with an exact list of mutations that must be performed. This list could be constructed in the `register` method and the `filter` method would just go through that list of mutations to perform.

So, for example, if there is only one mutation to do, say a `remove`, then only the remove mutation would be called instead of evaluating 12 `if` statements.

**Comment by talevy** [comment]
is #70 what you had in mind?

**Comment by talevy** [comment]
Closing after performance benchmarks show this not to be necessarily faster, and it complicates the flow. closing.
