### ISSUE TITLE
Add de-dot functionality

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-filter-mutate#54]
Many users are finding that Elasticsearch 2.0 will not accept field names with dots `.` in them.

We should add a de-dot method to the mutate filter to replace dots in field names with a user-definable separator.

**Comment by jordansissel** [comment]
I feel that we should make that function a separate filter. Mutate's already overloaded ;P

**Comment by untergeek** [comment]
So, not in both.  Just in a de-dot filter?

**Comment by jordansissel** [comment]
Yeah I think so. A field... renaming (?) filter could be cool, but we don't have to solve it in a general way yet, version 1 could just be "replace_dot" or something that allows you to set a replacement text instead of period in field names.

**Comment by untergeek** [comment]
Very good, then.  I will create a new plugin instead.
